name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  docker-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run gitlakes docker	    
      uses: docker://zricethezav/gitleaks
      with:
        args: gitleaks detect --source /github/workspace/
  # checkout:
  #   name: gitleaks-checkout
  #   runs-on: ubuntu-latest
  #    image: zricethezav/gitleaks
  #     volumes:
  #       - %PWD%:/test
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: gitleaks detect
  #       run: |
  #         pwd
  #         ls -al /github/workspace/
  #         gitleaks detect --source /test
  # scan:
  #   name: gitleaks-scan
  #   runs-on: ubuntu-latest
  #   container:
  #     image: zricethezav/gitleaks
  #     volumes:
  #       - %PWD%:/test
  #   steps:
  #     - name: gitleaks detect
  #       run: |
  #         pwd
  #         ls -al /test
  #         gitleaks detect --source /test