name: git-secrets
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: git-secrets
    runs-on: ubuntu-latest
    container:
      image: izhar0407/git-secrets
    steps:
      - name: git-secrets run
        run: |
          git clone https://github.com/ETConsulting/secret-scanning.git
          cd secret-scanning
          git secrets --install
          git secrets --register-aws
          git secrets --add 'MyPASSWORD[0-9]+'
          git-secrets --scan