name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  docker-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run gitlakes docker	    
      uses: docker://zricethezav/gitleaks
      with:
        args: detect --source /github/workspace/ --no-git