name: git-secrets
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: git-secrets
    runs-on: ubuntu-latest
    container:
      image: izhar0407/git-secrets
    steps:
      - name: Force Install GIT latest
        run: |
           apt-get update
           apt-get install -y git
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      - name: git-secrets run
        run: |
          ls -al
          git clone https://github.com/ETConsulting/secret-scanning.git
          git secrets --install
          git secrets --register-aws
          git secrets --add 'MyPASSWORD[0-9]+'
          git-secrets --scan

      