name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks-scan
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks
    steps:
      - name: gitleaks detect
        run: |
          git clone https://github.com/ETConsulting/secret-scanning.git
          cd secret-scanning
          gitleaks detect