name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks-scan
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks
    steps:
      - name: gitleaks detect
        run: |
          ls -al
          git clone https://github.com/ETConsulting/secret-scanning.git repo
          cd repo
          gitleaks detect