name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  checkout:
    name: gitleaks-checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  scan:
    name: gitleaks-scan
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks
      volumes:
        - ${PWD}:/test
    steps:
      - name: gitleaks detect
        run: |
          pwd
          ls -al /test
          gitleaks detect --source /test